<?php
/**
 * @var $this \Zend\View\Renderer\PhpRenderer
 */

$this->headTitle( $title = $this->translate(
    'admin.navTop.settings.facebook',
    'admin'
) );

$this->headTitle( $subTitle = $this->translate(
    'facebook.form.settings.title',
    'facebook'
) );

?>
<h1><?= $this->escapeHtml( $title ) ?></h1>
<div class="page">
    <h3><?= $this->escapeHtml( $subTitle ) ?></h3>
    <?= $this->form( $this->form, 'facebook' ) ?>
</div>
